name: 'Hello World'
description: 'Greet someone'
inputs:
  my-input:  # id of input
    description: 'An input'
    required: true
    default: 'foo'
outputs:
  my-output:
    description: "An output"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Checking for dead linkgs
      id: check
      run: python ${{ github.action_path }}/main.py
      shell: bash
    #   shell: bash
    # - id: random-number-generator
    #   run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #   shell: bash
    # - run: ${{ github.action_path }}/goodbye.sh
    #   shell: bash
