on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Do My stuff
        uses: FrancescoSaverioZuppichini/custom-github-action@main
        with:
          my-input: 'Mona the Octocat'
    